name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    environment:
      name: test
    name: Automated test action
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test
        uses: zitcha/github-action-read-deployments@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          deployment_environment: test

      - name: Use vars
        shell: bash
        run: |
          echo "deployment_created_at"    
          echo "${{ env.deployment_created_at }}"    
          
